import type { Metadata } from "next";
import { Jost, Caveat } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/views/Footer";

const jost = Jost({
  subsets: ["latin"],
  variable: "--font-jost-sans",
});

const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-caveat-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` ${caveat.variable} ${jost.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
          <Footer />

        </ThemeProvider>
      </body>
    </html>
  );
}
